### ISSUE TITLE
Specify version

### ISSUE THREAD

**Issue by ericclemmons** [ramasilveyra/gitpkg#16]
Love this project!  I've been experimenting with ways for https://github.com/aws-amplify/amplify-js/ to publish PR-previews (where each commit of a PR gets published artifacts so customers can validate PRs _before_ merging), and I think this project could be perfect.

For a PR, I would like customize the following:
https://github.com/ramasilveyra/gitpkg/blob/9c02f228fd8f6a4f31d35631a9a2f95a76ca7adb/src/tasks/Publish/get-git-tag-name.js#L3-L5

What's the best way could be handled?  I'm happy to submit a PR so we could support some convention like `1.2.3-PR456-abc789` that would help us prune releases after they're respective PRs have been merged...

**Comment by ramasilveyra** [comment]
Hello @ericclemmons! Sorry for the delay. @thejsn just opened a pr that will allow this https://github.com/ramasilveyra/gitpkg/pull/17. Do you need to keep support for node v6? if not I'm thinking on releasing that as a breaking change.

**Comment by ericclemmons** [comment]
@ramasilveyra Nope, only supporting Node LTS' myself!

**Comment by ramasilveyra** [comment]
thanks to @thejsn it should be possible to set custom version with https://github.com/ramasilveyra/gitpkg/tree/v1.0.0-beta.2#gettagname in [v1.0.0-beta.2](https://github.com/ramasilveyra/gitpkg/blob/v1.0.0-beta.2/CHANGELOG.md#100-beta2-2020-03-30).
